var config = {
    preButton: {
        _comment: "pre image",
        type: "button",
    },
    nextButton: {
        _comment: "next image",
        type: "button",
    },
    centerButton: {
        _comment: "center image",
        type: "button",
    },
    preButton: {
        _comment: "image index",
        type: "button",
    },
    index: {
        _comment: "image index",
        value: 0,
        valueType: 'number',
        min: 0,
        max: 30,
        type: "range",
    },
    offset: {
        _comment: "canvas offset",
        value: 2,
        valueType: 'number',
        min: 2,
        max: 30,
        type: "range",
    },
    imageOffset: {
        _comment: "image offset",
        value: 20,
        valueType: 'number',
        min: -100,
        max: 100,
        type: "range",
    },
    shadowOffset: {
        _comment: "shadow offset",
        value: 3,
        valueType: 'number',
        min: -50,
        max: 50,
        type: "range",
    },
    shadowBlur: {
        _comment: "shadow blur level",
        value: 5,
        valueType: 'number',
        min: 0,
        max: 30,
        type: "range",
    },
    shadowColorAlpha: {
        _comment: "shadow color alpha",
        value: 4,
        valueType: 'number',
        min: 0,
        max: 10,
        type: "range",
    },
    shadowColor: {
        _comment: "shadow color",
        value: 'black',
        valueType: 'string',
        type: "input",
    },
    borderLength: {
        _comment: "border length:",
        value: 1,
        valueType: 'number',
        min: 0,
        max: 30,
        type: "range",
    },
    borderColor: {
        _comment: "border color",
        value: 'grey',
        valueType: 'string',
        type: "input",
    },
}
